theme:
  name: material
  favicon: favicon.ico
  logo: images/archer2_white_transparent.png
  palette:
    scheme: default
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/archer2.css

site_name: ARCHER2 User Documentation
repo_url: https://github.com/ARCHER2-HPC/archer2-docs
repo_name: ARCHER2-HPC/archer2-docs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARCHER2-HPC
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ARCHER2_HPC
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/13848871/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - "Documentation overview": index.md
  - "Quickstart":
    - quick-start/quickstart-users.md
    - quick-start/quickstart-developers.md
  - "User and Best Practice Guide":
    - "Connecting to ARCHER2": user-guide/connecting.md
    - "Data management and transfer": user-guide/data.md
    - "Software environment": user-guide/sw-environment.md
    - "Running jobs on ARCHER2": user-guide/scheduler.md
    - "I/O and file systems": user-guide/io.md
    - "Application development environment": user-guide/dev-environment.md
    - "Containers": user-guide/containers.md
    - "Using Python": user-guide/python.md
    - "Data analysis": user-guide/analysis.md
    - "Debugging": user-guide/debug.md
    - "Profiling": user-guide/profile.md
    - "Performance tuning": user-guide/tuning.md
  - "Research Software":
    - "CASTEP": castep/castep.md
    - "Chemshell": chemshell/chemshell.md
    - "Code_Saturne": code-saturne/code-saturne.md
    - "CP2K": cp2k/cp2k.md
    - "ELK": elk/elk.md
    - "FEniCS": fenics/fenics.md
    - "GROMACS": gromacs/gromacs.md
    - "LAMMPS": lammps/lammps.md
    - "MITgcm": mitgcm/mitgcm.md
    - "Met Office Unified Model": mo-unified-model/mo-unified-model.md
    - "NAMD": namd/namd.md
    - "Nektar++": nektar++/nektar++.md
    - "NEMO": nemo/nemo.md
    - "NWChem": nwchem/nwchem.md
    - "ONETEP": onetep/onetep.md
    - "OpenFOAM": openfoam/openfoam.md
    - "Quantum Espresso": qe/qe.md
    - "VASP": vasp/vasp.md
  - "Software Libraries": overview.md
  - "Data Analysis and Tools": overview.md


